-- This resource was generated by grzyClothTool :)
-- https://discord.gg/HCQutNhxWt

fx_version 'cerulean'
game 'gta5'
author 'grzyClothTool'

files {
  'mp_m_freemode_01_snipyaddons_01.meta',
  'mp_f_freemode_01_snipyaddons_01.meta',
  'mp_m_freemode_01_snipyaddons_02.meta',
  'mp_f_freemode_01_snipyaddons_02.meta',
  'mp_f_freemode_01_snipyaddons_03.meta',
  'first_person_alternates_snipyaddons.meta'
}

data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_m_freemode_01_snipyaddons_01.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_snipyaddons_01.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_m_freemode_01_snipyaddons_02.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_snipyaddons_02.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_snipyaddons_03.meta'
data_file 'PED_FIRST_PERSON_ALTERNATE_DATA' 'first_person_alternates_snipyaddons.meta'
