AddTextEntry("WEAPON_VP9", "vp9")
AddTextEntry("WEAPON_KARAMBITKNIFE", "Karambit Knife")
AddTextEntry("WEAPON_HK416", "HK-416")
AddTextEntry("WEAPON_SLEDGEHAMMER", "Sledge Hammer")
AddTextEntry("WEAPON_KATANA", "Katana")
AddTextEntry("WEAPON_M9A3", "BERETTA M9A3")
AddTextEntry("WEAPON_G17GEN5", "Glock 17 Gen 5")
AddTextEntry("WEAPON_FIREAXE", "Fire Axe")
AddTextEntry("WEAPON_BREN", "Bren")
AddTextEntry("WEAPON_DOUBLEBARREL", "Double Barrel")
AddTextEntry("WEAPON_SCAR17FM", "Scar-17S")
AddTextEntry("WEAPON_GLITCHPOPVANDAL", "Glitchpop")
AddTextEntry("WEAPON_AR15", "AR-15")
AddTextEntry("WEAPON_HONEYBADGERCOD", "Honey Badger COD")
AddTextEntry("WEAPON_MP5SDFM", "MP5-SD")
AddTextEntry("WEAPON_FN509", "FN-509")
AddTextEntry("WEAPON_AK47NEONRIDE", "AK-47 Neon Ride")
AddTextEntry("WEAPON_AWPREDLINE", "AWP Redline")
