-- --╔════════════════════════════════════════════════════════════════════════════════╗

-- -- ██████╗ ██╗ ██████╗████████╗██╗   ██╗██████╗ ███████╗███████╗
-- -- ██╔══██╗██║██╔════╝╚══██╔══╝██║   ██║██╔══██╗██╔════╝██╔════╝
-- -- ██████╔╝██║██║        ██║   ██║   ██║██████╔╝█████╗  ███████╗
-- -- ██╔═══╝ ██║██║        ██║   ██║   ██║██╔══██╗██╔══╝  ╚════██║
-- -- ██║     ██║╚██████╗   ██║   ╚██████╔╝██║  ██║███████╗███████║
-- -- ╚═╝     ╚═╝ ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝
                                                             

Config.Pictures = {

    ['cash'] = '/src/html/assets/icons/cash.png',
    ['black_money'] = '/src/html/assets/icons/black_money.png',
    ['pesos'] = '/src/html/assets/icons/pesos.png',
    ['boombox'] = '/src/html/assets/icons/boombox.png',
    ['idcard'] = '/src/html/assets/icons/idcard.png',
    ['bmx'] = '/src/html/assets/icons/bmx.png',
    ['bodycam'] = '/src/html/assets/icons/bodycam.png',

    --###### DROGUES #####
    ["5fromages"] = '/src/html/assets/icons/5fromages.png',
    ["accesscard"] = '/src/html/assets/icons/accesscard.png',
    ["anchois"] = '/src/html/assets/icons/anchois.png',
    ["bandage"] = '/src/html/assets/icons/bandage.png',
    ["bar"] = '/src/html/assets/icons/bar.png',
    ["bijoux"] = '/src/html/assets/icons/bijoux.png',
    ["phone"] = '/src/html/assets/icons/phone.png',
    ["poissonchat"] = '/src/html/assets/icons/poissonchat.png',
    ["silure"] = '/src/html/assets/icons/silure.png',
    ["canneapeche"] = '/src/html/assets/icons/canneapeche.png',
    ["canneapechecarbonne"] = '/src/html/assets/icons/canneapechecarbonne.png',
    ["canneapecheoretcarbonne"] = '/src/html/assets/icons/canneapecheoretcarbonne.png',
    ["weed"] = '/src/html/assets/icons/weed.png',
    ["weed_pooch"] = '/src/html/assets/icons/weed_pooch.png',

    ["hashish"] = '/src/html/assets/icons/hashish.png',
    ["hashish_pooch"] = '/src/html/assets/icons/hashish_pooch.png',
    ["medikit"] = '/src/html/assets/icons/medikit.png',
    ["nitrovehicle"] = '/src/html/assets/icons/nitrovehicle.png',
    ["ciseaux"] = '/src/html/assets/icons/ciseaux.png',
    ["pepsi"] = '/src/html/assets/icons/pepsi.png',
    ["sprite"] = '/src/html/assets/icons/sprite.png',
    ["cappuccino"] = '/src/html/assets/icons/cappuccino.png',
    ["heineken"] = '/src/html/assets/icons/heineken.png',
    ["caprisun"] = '/src/html/assets/icons/caprisun.png',
    ["water"] = '/src/html/assets/icons/water.png',
    ["icetea"] = '/src/html/assets/icons/icetea.png',
    ["rhumcoca"] = '/src/html/assets/icons/rhumcoca.png',
    ["vodkafruit"] = '/src/html/assets/icons/vodkafruit.png',
    ["vodkaenergy"] = '/src/html/assets/icons/vodkaenergy.png',
    ["tequila"] = '/src/html/assets/icons/tequila.png',

    ["vinrouge"] = '/src/html/assets/icons/vinrouge.png',
    ["vinblanc"] = '/src/html/assets/icons/vinblanc.png',
    ["vinrose"] = '/src/html/assets/icons/vinrose.png',
    ["bolchips"] = '/src/html/assets/icons/bolchips.png',
    ["coca"] = '/src/html/assets/icons/coca.png',
    ["fanta"] = '/src/html/assets/icons/fanta.png',
    
    ["kevlar"] = '/src/html/assets/icons/kevlar.png',
    ["kevlarmid"] = '/src/html/assets/icons/kevlarmid.png',
    ["kevlarlow"] = '/src/html/assets/icons/kevlarlow.png',

    ["burgershot_frite"] = '/src/html/assets/icons/burgershot_frite.png',
    ["burgershot_oignonrings"] = '/src/html/assets/icons/burgershot_oignonrings.png',
    ["alive_chicken"] = '/src/html/assets/icons/alive_chicken.png',
    ["barbecue"] = '/src/html/assets/icons/barbecue.png',
    ['bolchips'] = '/src/html/assets/icons/bolchips.png',
    ["burgershot_coca"] = '/src/html/assets/icons/burgershot_coca.png',
    ["burgershot_cookie"] = '/src/html/assets/icons/burgershot_cookie.png',
    ["burgershot_milkshake"] = '/src/html/assets/icons/burgershot_milkshake.png',
    ["burgershot_pain"] = '/src/html/assets/icons/burgershot_pain.png',
    ["burgershot_painburger"] = '/src/html/assets/icons/burgershot_painburger.png',
    ["burgershot_salade"] = '/src/html/assets/icons/burgershot_salade.png',
    ["burgershot_sprite"] = '/src/html/assets/icons/burgershot_sprite.png',
    ["burgershot_tomate"] = '/src/html/assets/icons/burgershot_tomate.png',
    ["burgershot_viandeburger"] = '/src/html/assets/icons/burgershot_viandeburger.png',

    ["cerf"] = '/src/html/assets/icons/cerf.png',
    ["lapin"] = '/src/html/assets/icons/lapin.png',
    ["jaguar"] = '/src/html/assets/icons/jaguar.png',
    ["loup"] = '/src/html/assets/icons/loup.png',
    ["sanglier"] = '/src/html/assets/icons/sanglier.png',

    ["jumelles"] = '/src/html/assets/icons/jumelles.png',
    ["oblivionPill"] = '/src/html/assets/icons/oblivionPill.png',
    ["bread"] = '/src/html/assets/icons/bread.png',
    ["casino_burger"] = '/src/html/assets/icons/casino_burger.png',
    ["frite"] = '/src/html/assets/icons/frite.png',
    ["drink_burgershot"] = '/src/html/assets/icons/drink_burgershot.png',
    ["burgershot_burger"] = '/src/html/assets/icons/burgershot_burger.png',
    ["burgershot_cheddar"] = '/src/html/assets/icons/burgershot_cheddar.png',

    -- weapon
    ['shotgun_ammo'] = '/src/html/assets/icons/shotgun_ammo.png',
    ['rifle_ammo'] = '/src/html/assets/icons/rifle_ammo.png',
    ['mg_ammo'] = '/src/html/assets/icons/mg_ammo.png',
    ['smg_ammo'] = '/src/html/assets/icons/smg_ammo.png',
    ['sniper_ammo'] = '/src/html/assets/icons/sniper_ammo.png',
    ['pistol_ammo'] = '/src/html/assets/icons/pistol_ammo.png',

    ['carbinerifle'] = '/src/html/assets/icons/carbinerifle.png',
    ['advancedrifle'] = '/src/html/assets/icons/advancedrifle.png',
    ['assaultrifle'] = '/src/html/assets/icons/assaultrifle.png',
    ['assaultrifles'] = '/src/html/assets/icons/assaultrifles.png',
    ['assaultshotgun'] = '/src/html/assets/icons/assaultshotgun.png',
    ['assaultsmg'] = '/src/html/assets/icons/assaultsmg.png',
    ['bat'] = '/src/html/assets/icons/bat.png',
    ['battleaxe'] = '/src/html/assets/icons/battleaxe.png',
    ['bottle'] = '/src/html/assets/icons/bottle.png',
    ['ceramicpistol'] = '/src/html/assets/icons/ceramicpistol.png',
    ['combatpdw'] = '/src/html/assets/icons/combatpdw.png',
    ['combatpistol'] = '/src/html/assets/icons/combatpistol.png',
    ['compactrifle'] = '/src/html/assets/icons/compactrifle.png',
    ['crowbar'] = '/src/html/assets/icons/crowbar.png',
    ['dagger'] = '/src/html/assets/icons/dagger.png',
    ['knuckle'] = '/src/html/assets/icons/knuckle.png',
    ['flashlight'] = '/src/html/assets/icons/flashlight.png',
    ['golfclub'] = '/src/html/assets/icons/golfclub.png',
    ['hammer'] = '/src/html/assets/icons/hammer.png',
    ['hatchet'] = '/src/html/assets/icons/hatchet.png',
    ['bullpupshotgun'] = '/src/html/assets/icons/bullpupshotgun.png',
    ['heavypistol'] = '/src/html/assets/icons/heavypistol.png',
    ['knife'] = '/src/html/assets/icons/knife.png',
    ['machete'] = '/src/html/assets/icons/machete.png',
    ['machinepistol'] = '/src/html/assets/icons/machinepistol.png',
    ['microsmg'] = '/src/html/assets/icons/microsmg.png',
    ['militaryrifle'] = '/src/html/assets/icons/militaryrifle.png',
    ['minismg'] = '/src/html/assets/icons/minismg.png',
    ['musket'] = '/src/html/assets/icons/musket.png',
    ['nightstick'] = '/src/html/assets/icons/nightstick.png',
    ['petrolcan'] = '/src/html/assets/icons/petrolcan.png',
    ['revolver'] = '/src/html/assets/icons/revolver.png',
    ['pistol'] = '/src/html/assets/icons/pistol.png',
    ['pistol_mk2'] = '/src/html/assets/icons/pistol_mk2.png',
    ['pistol50'] = '/src/html/assets/icons/pistol50.png',
    ['poolcue'] = '/src/html/assets/icons/poolcue.png',
    ['pumpshotgun'] = '/src/html/assets/icons/pumpshotgun.png',
    ['sawnoffshotgun'] = '/src/html/assets/icons/sawnoffshotgun.png',
    ['specialcarbine'] = '/src/html/assets/icons/specialcarbine.png',
    ['stungun'] = '/src/html/assets/icons/stungun.png',
    ['smg'] = '/src/html/assets/icons/smg.png',
    ['smg_mk2'] = '/src/html/assets/icons/smg_mk2.png',
    ['snspistol'] = '/src/html/assets/icons/snspistol.png',
    ['snspistol_mk2'] = '/src/html/assets/icons/snspistol_mk2.png',
    ['switchblade'] = '/src/html/assets/icons/switchblade.png',
    ['wrench'] = '/src/html/assets/icons/wrench.png',
    ['gadgetpistol'] = '/src/html/assets/icons/gadgetpistol.png',
    ['doubleaction'] = '/src/html/assets/icons/doubleaction.png',
    ['navyrevolver'] = '/src/html/assets/icons/navyrevolver.png',
    ['stone_hatchet'] = '/src/html/assets/icons/stone_hatchet.png',
    ['stungun_02'] = '/src/html/assets/icons/stungun_02.png',
    ['combatpistolpol'] = '/src/html/assets/icons/combatpistolpol.png',
       
    ['pants'] = '/src/html/assets/icons/pants.png',
    ['top'] = '/src/html/assets/icons/top.png',
    ['shoes'] = '/src/html/assets/icons/shoes.png',
    ['helmet'] = '/src/html/assets/icons/helmet.png',
    ['glasses'] = '/src/html/assets/icons/glasses.png',
    ['outfit'] = '/src/html/assets/icons/outfit.png',
    ['mask'] = '/src/html/assets/icons/mask.png',
    ['bags'] = '/src/html/assets/icons/bags.png',
    ['watches'] = '/src/html/assets/icons/watches.png',
    ['ears'] = '/src/html/assets/icons/ears.png',
    ['chain'] = '/src/html/assets/icons/chain.png',
    ['bracelets'] = '/src/html/assets/icons/bracelets.png',

    -- ACCESSOIRE ARMES
    ['accessory_clip'] = '/src/html/assets/icons/accessory_clip.png',
    ['accessory_clip_drum'] = '/src/html/assets/icons/accessory_clip_drum.png',
    ['accessory_flashlight'] = '/src/html/assets/icons/accessory_flashlight.png',
    ['accessory_suppressor'] = '/src/html/assets/icons/accessory_suppressor.png',
    ['accessory_scope'] = '/src/html/assets/icons/accessory_scope.png',
    ['accessory_grip'] = '/src/html/assets/icons/accessory_grip.png',

    ---------Arme modée-----------
    ['doublebarrel'] = '/src/html/assets/icons/doublebarrel.png',
    ['honeybadgercod'] = '/src/html/assets/icons/honeybadgercod.png',
    ['scar17fm'] = '/src/html/assets/icons/scar17fm.png',
    ['fireaxe'] = '/src/html/assets/icons/fireaxe.png',
    ['fn509'] = '/src/html/assets/icons/fn509.png',
    ['vp9'] = '/src/html/assets/icons/vp9.png',
    ['ar15'] = '/src/html/assets/icons/ar15.png',

    ---------DROGUE-----------
    ['empty_bag'] = '/src/html/assets/icons/empty_bag.png',
    ["cokepure"] = '/src/html/assets/icons/cokepure.png',
    ['cokepur'] = '/src/html/assets/icons/cokepur.png',
    ['cokecoupe'] = '/src/html/assets/icons/cokecoupe.png',
    ['coke_pooch'] = '/src/html/assets/icons/coke_pooch.png',
    ['coca_blend'] = '/src/html/assets/icons/coca_blend.png',
    ['coca_leaf'] = '/src/html/assets/icons/coca_leaf.png',
    ['coca_paste'] = '/src/html/assets/icons/coca_paste.png',
    ['hydrochloric_acid'] = '/src/html/assets/icons/hydrochloric_acid.png',
    ['gasoline'] = '/src/html/assets/icons/gasoline.png',
    ['cement'] = '/src/html/assets/icons/cement.png',
    ['feuillecoca'] = '/src/html/assets/icons/feuillecoca.png',
    ['feuillechanvre'] = '/src/html/assets/icons/feuillechanvre.png',
    ['pure_meth_pills'] = '/src/html/assets/icons/pure_meth_pills.png',
    ['phosphorerouge'] = '/src/html/assets/icons/phosphorerouge.png',
    ['terre'] = '/src/html/assets/icons/terre.png',
    ['kq_acetone'] = '/src/html/assets/icons/kq_acetone.png',
    ['kq_ammonia'] = '/src/html/assets/icons/kq_ammonia.png',
    ['kq_ethanol'] = '/src/html/assets/icons/kq_ethanol.png',
    ['kq_lithium'] = '/src/html/assets/icons/kq_lithium.png',
    ['kq_meth_pills'] = '/src/html/assets/icons/kq_meth_pills.png',
    ['kq_meth_lab_kit'] = '/src/html/assets/icons/kq_meth_lab_kit.png',
    ['kq_meth_low'] = '/src/html/assets/icons/kq_meth_low.png',
    ['kq_meth_mid'] = '/src/html/assets/icons/kq_meth_mid.png',
    ['kq_meth_high'] = '/src/html/assets/icons/kq_meth_high.png',
    ['methpure'] = '/src/html/assets/icons/methpure.png',
    
    ['hack_laptop'] = '/src/html/assets/icons/hack_laptop.png',
    ['hack_phone'] = '/src/html/assets/icons/hack_phone.png',

    -- Pêche
    ['douce_lures'] = '/src/html/assets/icons/douce_lures.png',
    ['mer_lures'] = '/src/html/assets/icons/mer_lures.png',
    ['ocean_lures'] = '/src/html/assets/icons/ocean_lures.png',

    ['crochetage_kit'] = '/src/html/assets/icons/crochetage_kit.png',
    ['repairkit'] = '/src/html/assets/icons/repairkit.png',
    ['kitcarro'] = '/src/html/assets/icons/kitcarro.png',
    ['tablet'] = '/src/html/assets/icons/tablet.png',
}

--╚════════════════════════════════════════════════════════════════════════════════╝