-- --╔════════════════════════════════════════════════════════════════════════════════╗

-- -- ██████╗ ██╗ ██████╗████████╗██╗   ██╗██████╗ ███████╗███████╗
-- -- ██╔══██╗██║██╔════╝╚══██╔══╝██║   ██║██╔══██╗██╔════╝██╔════╝
-- -- ██████╔╝██║██║        ██║   ██║   ██║██████╔╝█████╗  ███████╗
-- -- ██╔═══╝ ██║██║        ██║   ██║   ██║██╔══██╗██╔══╝  ╚════██║
-- -- ██║     ██║╚██████╗   ██║   ╚██████╔╝██║  ██║███████╗███████║
-- -- ╚═╝     ╚═╝ ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝
                                                             

Config.Pictures = {

    ['cash'] = '/src/html/assets/icons/money.png',
    ['black_money'] = '/src/html/assets/icons/black_money.png',
    ['pesos'] = '/src/html/assets/icons/pesos.png',
    ['boombox'] = '/src/html/assets/icons/boombox.png',
    ['idcard'] = '/src/html/assets/icons/idcard.png',
    ['bmx'] = '/src/html/assets/icons/bmx.png',
    ['bodycam'] = '/src/html/assets/icons/bodycam.png',

    --###### DROGUES #####
    ["5fromages"] = '/src/html/assets/icons/pizza.png',
    ["accesscard"] = '/src/html/assets/icons/security_card_01.png',
    ["anchois"] = '/src/html/assets/icons/fish_sardine.png',
    ["bandage"] = '/src/html/assets/icons/bandage.png',
    ["bar"] = '/src/html/assets/icons/fish_espadon.png',
    ["bijoux"] = '/src/html/assets/icons/jewels.png',
    ["phone"] = '/src/html/assets/icons/lbphone.png',
    ["poissonchat"] = '/src/html/assets/icons/fish_yellowperch.png',
    ["silure"] = '/src/html/assets/icons/fish_silure.png',
    ["canneapeche"] = '/src/html/assets/icons/fishing_road.png',
    ["canneapechecarbonne"] = '/src/html/assets/icons/fishing_road3.png',
    ["canneapecheoretcarbonne"] = '/src/html/assets/icons/fishing_road5.png',
    ["weed"] = '/src/html/assets/icons/weed.png',
    ["weed_pooch"] = '/src/html/assets/icons/weed_pooch.png',

    ["hashish"] = '/src/html/assets/icons/heroine.png',
    ["hashish_pooch"] = '/src/html/assets/icons/heroine_pooch.png',
    ["medikit"] = '/src/html/assets/icons/medikit.png',
    ["nitrovehicle"] = '/src/html/assets/icons/nitrovehicle.png',
    ["ciseaux"] = '/src/html/assets/icons/ciseaux.png',
    ["pepsi"] = '/src/html/assets/icons/cola.png',
    ["sprite"] = '/src/html/assets/icons/sprunk.png',
    ["cappuccino"] = '/src/html/assets/icons/coffee.png',
    ["heineken"] = '/src/html/assets/icons/beer_logger.png',
    ["caprisun"] = '/src/html/assets/icons/bubble_tea_orange.png',
    ["water"] = '/src/html/assets/icons/water.png',
    ["icetea"] = '/src/html/assets/icons/bubble_tea_orange.png',
    ["rhumcoca"] = '/src/html/assets/icons/rum.png',
    ["vodkafruit"] = '/src/html/assets/icons/vodka.png',
    ["vodkaenergy"] = '/src/html/assets/icons/vodka.png',
    ["tequila"] = '/src/html/assets/icons/tequila.png',


    ["vinrouge"] = '/src/html/assets/icons/wine.png',
    ["vinblanc"] = '/src/html/assets/icons/champagne.png',
    ["vinrose"] = '/src/html/assets/icons/wine.png',
    ["bolchips"] = '/src/html/assets/icons/chips.png',
    ["coca"] = '/src/html/assets/icons/cocacola.png',
    ["fanta"] = '/src/html/assets/icons/bubble_tea_orange.png',
    


    ["kevlar"] = '/src/html/assets/icons/armor.png',
    ["kevlarmid"] = '/src/html/assets/icons/armor.png',
    ["kevlarlow"] = '/src/html/assets/icons/armor.png',

    ["burgershot_frite"] = '/src/html/assets/icons/frites_burgershot.png',
    ["burgershot_oignonrings"] = '/src/html/assets/icons/onionrings.png',
    ["5fromages"] = '/src/html/assets/icons/pizza_slice.png',
    ["alive_chicken"] = '/src/html/assets/icons/viande_poulet_cru.png',
    ["barbecue"] = '/src/html/assets/icons/pizza_slice.png',
    ['bolchips'] = '/src/html/assets/icons/chips.png',
    ["burgershot_coca"] = '/src/html/assets/icons/cocacola.png',
    ["burgershot_cookie"] = '/src/html/assets/icons/cookie.png',
    ["burgershot_milkshake"] = '/src/html/assets/icons/milkshake.png',
    ["burgershot_pain"] = '/src/html/assets/icons/bread.png',
    ["burgershot_painburger"] = '/src/html/assets/icons/bread.png',
    ["burgershot_salade"] = '/src/html/assets/icons/salad.png',
    ["burgershot_sprite"] = '/src/html/assets/icons/sprite.png',
    ["burgershot_tomate"] = '/src/html/assets/icons/tomato.png',
    ["burgershot_viandeburger"] = '/src/html/assets/icons/viande_1.png',


    ["cerf"] = '/src/html/assets/icons/hunting_deer_pelt_1.png',
    ["lapin"] = '/src/html/assets/icons/hunting_rabbit_pelt_1.png',
    ["jaguar"] = '/src/html/assets/icons/hunting_deer_pelt_3.png',
    ["loup"] = '/src/html/assets/icons/hunting_wolf_pelt_1.png',
    ["sanglier"] = '/src/html/assets/icons/hunting_wolf_pelt_3.png',



    ["jumelles"] = '/src/html/assets/icons/binoculars.png',
    ["oblivionPill"] = '/src/html/assets/icons/ephedrine.png',
    ["bread"] = '/src/html/assets/icons/bread.png',
    ["casino_burger"] = '/src/html/assets/icons/burger_chicken.png',
    ["frite"] = '/src/html/assets/icons/frites_burgershot.png',
    ["drink_burgershot"] = '/src/html/assets/icons/drink_burgershot.png',
    ["burgershot_burger"] = '/src/html/assets/icons/burger_love.png',
    ["burgershot_cheddar"] = '/src/html/assets/icons/cheese.png',

    -- weapon
    ['shotgun_ammo'] = '/src/html/assets/images/12gauge.png',
    ['rifle_ammo'] = '/src/html/assets/images/ammo_50BMG.png',
    ['mg_ammo'] = '/src/html/assets/images/68kal.png',
    ['smg_ammo'] = '/src/html/assets/images/556mm.png',
    ['sniper_ammo'] = '/src/html/assets/images/762mm.png',
    ['pistol_ammo'] = '/src/html/assets/images/9mm.png',

    ['glockdm'] = '/src/html/assets/icons/glockdm.png',
    ['slide_guitare'] = '/src/html/assets/icons/GuitareWeap.png',
    ['smgslide'] = '/src/html/assets/icons/weapon_smg.png',
    ['tec9mf'] = '/src/html/assets/icons/tec9mf.png',
    ['militarm4'] = '/src/html/assets/icons/militarm4.png',
    ['shotgunk'] = '/src/html/assets/icons/shotgunk.png',
    ['penis'] = '/src/html/assets/icons/penis.png',
    ['coachgun'] = '/src/html/assets/icons/coachgun.png',
    ['scarsc'] = '/src/html/assets/icons/scarsc.png',
    ['oblivion'] = '/src/html/assets/icons/oblivion.png',
    ['carbinerifle'] = '/src/html/assets/icons/weapon_carbinerifle.png',
    ['advancedrifle'] = '/src/html/assets/icons/AdvancedRifle.png',
    ['assaultrifle'] = '/src/html/assets/icons/weapon_assaultrifle.png',
    ['assaultrifles'] = '/src/html/assets/icons/AssaultRifleMkII.png',
    ['assaultshotgun'] = '/src/html/assets/icons/weapon_assaultshotgun.png',
    ['assaultsmg'] = '/src/html/assets/icons/weapon_assaultsmg.png',
    ['bat'] = '/src/html/assets/icons/weapon_bat.png',
    ['battleaxe'] = '/src/html/assets/icons/weapon_battleaxe.png',
    ['bottle'] = '/src/html/assets/icons/weapon_bottle.png',
    ['ceramicpistol'] = '/src/html/assets/icons/weapon_ceramicpistol.png',
    ['combatpdw'] = '/src/html/assets/icons/weapon_combatpdw.png',
    ['combatpistol'] = '/src/html/assets/icons/weapon_combatpistol.png',
    ['compactrifle'] = '/src/html/assets/icons/weapon_compactrifle.png',
    ['crowbar'] = '/src/html/assets/icons/weapon_crowbar.png',
    ['dagger'] = '/src/html/assets/icons/weapon_dagger.png',
    ['knuckle'] = '/src/html/assets/icons/weapon_knuckle.png',
    ['flashlight'] = '/src/html/assets/icons/weapon_flashlight.png',
    ['golfclub'] = '/src/html/assets/icons/weapon_golfclub.png',
    ['hammer'] = '/src/html/assets/icons/weapon_hammer.png',
    ['hatchet'] = '/src/html/assets/icons/weapon_hatchet.png',
    ['bullpupshotgun'] = '/src/html/assets/images/bullpupshotgun.png',
    ['heavypistol'] = '/src/html/assets/icons/weapon_heavypistol.png',
    ['knife'] = '/src/html/assets/icons/weapon_knife.png',
    ['machete'] = '/src/html/assets/icons/weapon_machete.png',
    ['machinepistol'] = '/src/html/assets/icons/weapon_machinepistol.png',
    ['microsmg'] = '/src/html/assets/icons/weapon_microsmg.png',
    ['militaryrifle'] = '/src/html/assets/icons/weapon_militaryrifle.png',
    ['minismg'] = '/src/html/assets/icons/weapon_minismg.png',
    ['musket'] = '/src/html/assets/icons/weapon_musket.png',
    ['nightstick'] = '/src/html/assets/icons/weapon_nightstick.png',
    ['petrolcan'] = '/src/html/assets/icons/weapon_petrolcan.png',
    ['revolver'] = '/src/html/assets/icons/weapon_revolver.png',
    ['pistol'] = '/src/html/assets/icons/weapon_pistol.png',
    ['pistol_mk2'] = '/src/html/assets/icons/weapon_pistol_mk2.png',
    ['pistol50'] = '/src/html/assets/icons/weapon_pistol50.png',
    ['poolcue'] = '/src/html/assets/icons/weapon_poolcue.png',
    ['pumpshotgun'] = '/src/html/assets/icons/weapon_pumpshotgun.png',
    ['sawnoffshotgun'] = '/src/html/assets/icons/weapon_sawnoffshotgun.png',
    ['specialcarbine'] = '/src/html/assets/icons/weapon_specialcarbine.png',
    ['stungun'] = '/src/html/assets/icons/weapon_stungun.png',
    ['smg'] = '/src/html/assets/icons/weapon_smg.png',
    ['smg_mk2'] = '/src/html/assets/icons/weapon_smg_mk2.png',
    ['snspistol'] = '/src/html/assets/icons/weapon_snspistol.png',
    ['snspistol_mk2'] = '/src/html/assets/icons/weapon_snspistol_mk2.png',
    ['switchblade'] = '/src/html/assets/icons/weapon_switchblade.png',
    ['wrench'] = '/src/html/assets/icons/weapon_wrench.png',
    ['gadgetpistol'] = '/src/html/assets/icons/weapon_gadgetpistol.png',
    ['doubleaction'] = '/src/html/assets/icons/weapon_doubleaction.png',
    ['navyrevolver'] = '/src/html/assets/icons/weapon_navyrevolver.png',
    ['stone_hatchet'] = '/src/html/assets/icons/weapon_stone_hatchet.png',
    ['stungun_02'] = '/src/html/assets/icons/weapon_stungun_02.png',
    ['aks74u'] = '/src/html/assets/icons/weapon_aks74u.png',
    ['dbshotgun'] = '/src/html/assets/item/weapon_doublebarrelfm.png',
    ['katana'] = '/src/html/assets/icons/weapon_katana.png',
    ['shotgunletal'] = '/src/html/assets/icons/weapon_shotgunletal.png',
    ['blacksniper'] = '/src/html/assets/icons/weapon_blacksniper.png',
    ['redl'] = '/src/html/assets/icons/weapon_redl.png',
    ['predator'] = '/src/html/assets/icons/weapon_predator.png',
    ['glock17'] = '/src/html/assets/icons/weapon_glock.png',
    ['hkump'] = '/src/html/assets/icons/weapon_hkump.png',
    ['scar17fm'] = '/src/html/assets/icons/weapon_scar17fm.png',
    ['honeybadgercod'] = '/src/html/assets/icons/weapon_honeybadgercod.png',
    ['fn509'] = '/src/html/assets/icons/weapon_fn509.png',
    ['mcxspear'] = '/src/html/assets/icons/weapon_mcxspear.png',
    ['g17neonoir'] = '/src/html/assets/icons/weapon_g17neonoir.png',
    ['ar15'] = '/src/html/assets/icons/weapon_ar15.png',
    ['m9bayonnetlore'] = '/src/html/assets/icons/weapon_m9bayonnetlore.png',
    ['m4a1mk2'] = '/src/html/assets/icons/weapon_m4a1mk2.png',
    ['g17gen5'] = '/src/html/assets/icons/weapon_g17gen5.png',
    ['fireaxe'] = '/src/html/assets/icons/weapon_fireaxe.png',
    ['hk416'] = '/src/html/assets/icons/weapon_hk416.png',
    ['bren'] = '/src/html/assets/icons/weapon_bren.png',
    ['combatpistolpol'] = '/src/html/assets/icons/weapon_combatpistol.png',    
       
    ['pants'] = 'assets/images/clothes_pants.png',
    ['top'] = 'assets/images/clothes_haut.png',
    ['shoes'] = 'assets/images/clothes_shoes.png',
    ['helmet'] = 'assets/images/hat.png',
    ['glasses'] = 'assets/images/clothes_glasses.png',
    ['outfit'] = 'assets/images/tenue.png',
    ['mask'] = 'assets/images/mask.png',
    ['bags'] = 'assets/images/bags.png',
    ['watches'] = 'assets/images/clothes_montre.png',
    ['ears'] = 'assets/images/clothes_earring.png',
    ['chain'] = 'assets/images/clothes_chaine.png',
    ['bracelets'] = 'assets/icons/bracelet.png',

    -- ACCESSOIRE ARMES
    ['accessory_clip'] = '/src/html/assets/icons/weapon_accessory_clip.png',
    ['accessory_clip_drum'] = '/src/html/assets/icons/weapon_accessory_clip_drum.png',
    ['accessory_flashlight'] = '/src/html/assets/icons/weapon_accessory_flashlight.png',
    ['accessory_suppressor'] = '/src/html/assets/icons/weapon_accessory_suppressor.png',
    ['accessory_scope'] = '/src/html/assets/icons/weapon_accessory_scope.png',
    ['accessory_grip'] = 'https://cdn.discordapp.com/attachments/1039007233335369789/1168603441820602458/attach_grip',

    ---------DROGUE-----------
    ['empty_bag'] = '/src/html/assets/icons/empty_bag.png',
    ["cokepure"] = '/src/html/assets/icons/cokepure.png',
    ['cokepur'] = '/src/html/assets/icons/cokepur.png',
    ['cokecoupe'] = '/src/html/assets/icons/cokecoupe.png',
    ['coke_pooch'] = '/src/html/assets/icons/coke_pooch.png',
    ['coca_blend'] = '/src/html/assets/icons/coca_blend.png',
    ['coca_leaf'] = '/src/html/assets/icons/coca_leaf.png',
    ['coca_paste'] = '/src/html/assets/icons/coca_paste.png',
    ['hydrochloric_acid'] = '/src/html/assets/icons/hydrochloric_acid.png',
    ['gasoline'] = '/src/html/assets/icons/gasoline.png',
    ['cement'] = '/src/html/assets/icons/cement.png',
    ['feuillecoca'] = '/src/html/assets/icons/feuillecoca.png',
    ['feuillechanvre'] = '/src/html/assets/icons/feuillechanvre.png',
    ['pure_meth_pills'] = '/src/html/assets/icons/pure_meth_pills.png',
    ['phosphorerouge'] = '/src/html/assets/icons/phosphorerouge.png',
    ['terre'] = '/src/html/assets/icons/terre.png',
    ['kq_acetone'] = '/src/html/assets/icons/kq_acetone.png',
    ['kq_ammonia'] = '/src/html/assets/icons/kq_ammonia.png',
    ['kq_ethanol'] = '/src/html/assets/icons/kq_ethanol.png',
    ['kq_lithium'] = '/src/html/assets/icons/kq_lithium.png',
    ['kq_meth_pills'] = '/src/html/assets/icons/kq_meth_pills.png',
    ['kq_meth_lab_kit'] = '/src/html/assets/icons/kq_meth_lab_kit.png',
    ['kq_meth_low'] = '/src/html/assets/icons/kq_meth_low.png',
    ['kq_meth_mid'] = '/src/html/assets/icons/kq_meth_mid.png',
    ['kq_meth_high'] = '/src/html/assets/icons/kq_meth_high.png',
    ['methpure'] = '/src/html/assets/icons/methpure.png',
    
    ['hack_laptop'] = '/src/html/assets/icons/hack_laptop.png',
    ['hack_phone'] = '/src/html/assets/icons/hack_phone.png',

    -- Pêche
    ['douce_lures'] = '/src/html/assets/images/bait_river.png',
    ['mer_lures'] = '/src/html/assets/images/bait_tropical.png',
    ['ocean_lures'] = '/src/html/assets/images/bait_sea.png',

    ['crochetage_kit'] = '/src/html/assets/images/crochetage_kit.png',
    ['repairkit'] = '/src/html/assets/images/repairkit.png',
    ['tablet'] = '/src/html/assets/images/tablet.png',
}

--╚════════════════════════════════════════════════════════════════════════════════╝