CREATE TABLE IF NOT EXISTS `lbtablet_police_offences_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `title` (`title`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `lbtablet_police_offences_categories` (`id`, `title`) VALUES
	(8, 'Cybercrimes'),
	(1, 'Drug-Related Offences'),
	(9, 'Environmental Offences'),
	(6, 'Miscellaneous Crimes'),
	(3, 'Property Crimes'),
	(10, 'Public Order Offences'),
	(4, 'Traffic Violations'),
	(7, 'Violent Crimes'),
	(2, 'Weapon-Related Offences'),
	(5, 'White-Collar Crimes');

CREATE TABLE IF NOT EXISTS `lbtablet_police_offences` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `category_id` int(10) unsigned NOT NULL,
  `class` varchar(100) NOT NULL,
  `title` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `fine` int(10) unsigned NOT NULL DEFAULT 0,
  `jail_time` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `category_id` (`category_id`,`class`,`title`),
  CONSTRAINT `lbtablet_police_offences_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `lbtablet_police_offences` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=118 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO lbtablet_police_offences (id, category_id, class, title, description, fine, jail_time) VALUES
	(1, 1, 'misdemeanor', 'Possession de substances contrôlées', 'Possession de drogues illégales pour usage personnel.', 10000, 0),
	(2, 1, 'infraction', 'Possession d’équipement lié à la drogue', 'Possession d’objets associés à l’usage ou à la préparation de drogues.', 4000, 0),
	(4, 1, 'felony', 'Conduite sous l’influence de drogues', 'Conduite d’un véhicule sous l’effet de drogues.', 20000, 12),
	(6, 1, 'misdemeanor', 'Usage de drogue en public', 'Consommation de drogues illégales dans des lieux publics.', 6000, 0),
	(8, 1, 'felony', 'Fraude à l’ordonnance médicale', 'Falsification d’ordonnances pour obtenir des substances contrôlées.', 20000, 24),
	(11, 1, 'felony', 'Vente publique de drogues', 'Vente de drogues illégales dans un espace public.', 40000, 36),
	(13, 2, 'felony', 'Vente illégale d’armes à feu', 'Vente d’armes sans les licences ou vérifications nécessaires.', 100000, 60),
	(14, 2, 'felony', 'Usage illégal d’une arme à feu', 'Décharge d’une arme dans des zones interdites ou dangereuses.', 80000, 36),
	(15, 2, 'felony', 'Possession d’une arme interdite', 'Possession d’armes illégales comme des explosifs ou fusils modifiés.', 100000, 48),
	(16, 2, 'misdemeanor', 'Exhibition d’arme', 'Montrer une arme de manière menaçante sans raison valable.', 15000, 12),
	(17, 2, 'misdemeanor', 'Utilisation d’arme sous influence', 'Manipulation d’une arme sous l’effet de drogues ou d’alcool.', 20000, 12),
	(18, 2, 'felony', 'Possession d’arme dans une zone restreinte', 'Transport d’armes dans des lieux strictement interdits comme des écoles.', 60000, 24),
	(19, 2, 'felony', 'Trafic illégal d’armes à feu', 'Transport ou vente illégale d’armes à travers les juridictions.', 140000, 72),
	(20, 2, 'misdemeanor', 'Non-sécurisation d’une arme à feu', 'Manque de stockage sécurisé d’une arme, permettant un accès non autorisé.', 10000, 0),
	(21, 2, 'felony', 'Modification illégale d’une arme', 'Altération d’une arme pour la rendre plus dangereuse, comme un mode automatique.', 120000, 48),
	(22, 2, 'felony', 'Possession d’arme sans numéro de série', 'Possession ou utilisation d’une arme avec numéro de série illisible.', 80000, 36),
	(23, 2, 'misdemeanor', 'Port d’arme chargée en public', 'Possession d’une arme chargée en public sans autorisation.', 40000, 24),
	(24, 2, 'misdemeanor', 'Usage négligent d’une arme', 'Manipulation d’une arme de manière imprudente, causant des risques pour autrui.', 30000, 12),
	(25, 2, 'felony', 'Possession d’arme volée', 'Possession d’une arme identifiée comme volée.', 100000, 36),
	(26, 3, 'misdemeanor', 'Vandalisme', 'Destruction ou dégradation intentionnelle de biens.', 20000, 0),
	(28, 3, 'felony', 'Incendie criminel', 'Incendie volontaire et malveillant de biens.', 40000, 48),
	(29, 3, 'misdemeanor', 'Vol à l’étalage', 'Vol de marchandises dans un commerce.', 6000, 0),
	(30, 3, 'infraction', 'Intrusion', 'Entrée ou séjour non autorisé sur une propriété.', 4000, 0),
	(32, 3, 'misdemeanor', 'Petit vol', 'Vol de biens de faible valeur.', 10000, 0),
	(33, 3, 'misdemeanor', 'Possession de biens volés', 'Possession d’objets volés appartenant à autrui.', 14000, 0),
	(34, 3, 'misdemeanor', 'Graffiti', 'Peinture ou dégradation illégale de biens publics ou privés.', 10000, 0),
	(35, 3, 'felony', 'Fraude à la carte bancaire', 'Utilisation de cartes bancaires volées ou falsifiées.', 40000, 24),
	(37, 3, 'misdemeanor', 'Piratage', 'Copie ou distribution illégale de contenu protégé par droits d’auteur.', 20000, 0),
	(38, 3, 'felony', 'Usurpation d’identité', 'Utilisation frauduleuse des informations personnelles de quelqu’un.', 40000, 48),
	(43, 4, 'infraction', 'Excès de vitesse', 'Dépassement des limites de vitesse autorisées.', 2000, 0),
	(44, 4, 'infraction', 'Non-respect d’un feu rouge', 'Ne pas s’arrêter à un feu rouge.', 4000, 0),
	(45, 4, 'felony', 'Conduite en état d’ivresse', 'Conduite sous l’effet de l’alcool ou de drogues.', 20000, 12),
	(46, 4, 'misdemeanor', 'Conduite dangereuse', 'Conduite avec mépris volontaire pour la sécurité.', 10000, 6),
	(47, 4, 'misdemeanor', 'Conduite sans permis', 'Conduite sans permis valide.', 5000, 0),
	(49, 4, 'infraction', 'Conduite sans assurance', 'Conduite sans couverture d’assurance valide.', 10000, 0),
	(50, 4, 'infraction', 'Non-respect de la priorité', 'Non-respect du droit de passage selon les lois.', 3000, 0),
	(51, 4, 'infraction', 'Demi-tour illégal', 'Effectuer un demi-tour là où c’est interdit.', 2000, 0),
	(52, 4, 'infraction', 'Absence de phares', 'Conduite sans phares la nuit ou par faible visibilité.', 1000, 0),
	(53, 4, 'felony', 'Course de rue', 'Participation à des courses illégales sur routes publiques.', 30000, 24),
	(54, 4, 'infraction', 'Conduite à contresens', 'Circulation en sens inverse de la circulation.', 4000, 0),
	(55, 4, 'infraction', 'Stationnement dans zones handicapées', 'Stationnement sans permis dans un espace réservé.', 4000, 0),
	(56, 4, 'misdemeanor', 'Incident de rage au volant', 'Conduite agressive mettant en danger d’autres usagers.', 15000, 6),
	(57, 4, 'infraction', 'Véhicule non enregistré', 'Conduite sans immatriculation valide.', 3000, 0),
	(58, 4, 'infraction', 'Vitres teintées excessivement', 'Teinte de vitres plus sombre que la réglementation.', 2000, 0),
	(95, 8, 'felony', 'Hameçonnage', 'Utilisation de faux messages pour obtenir des données sensibles.', 30000, 24),
	(96, 8, 'misdemeanor', 'Harcèlement en ligne', 'Menaces ou intimidations via Internet.', 10000, 0),
	(97, 8, 'felony', 'Accès non autorisé à des systèmes informatiques', 'Pirater des systèmes informatiques sans autorisation.', 60000, 48),
	(98, 9, 'infraction', 'Surpêche', 'Dépassement des quotas de pêche autorisés.', 10000, 0),
	(102, 9, 'misdemeanor', 'Dépôt illégal de déchets', 'Élimination de déchets dans des zones non autorisées.', 15000, 0),
	(103, 9, 'felony', 'Braconnage', 'Chasse ou capture illégale de la faune.', 80000, 36),
	(104, 10, 'misdemeanor', 'Conduite désordonnée', 'Comportement perturbateur ou indiscipliné en public.', 6000, 0),
	(105, 10, 'infraction', 'Ivresse publique', 'État d’ébriété visible ou d’altération en public.', 3000, 0),
	(106, 10, 'infraction', 'Flânage', 'Stationnement prolongé sans but légitime.', 1000, 0),
	(107, 10, 'infraction', 'Trouble à l’ordre public', 'Comportement bruyant ou perturbateur en public.', 2000, 0),
	(109, 10, 'misdemeanor', 'Participation à une émeute', 'Engagement ou encouragement à des actes violents en foule.', 20000, 12),
	(112, 10, 'infraction', 'Conduite indécente', 'Comportement offensant ou obscène en public.', 2000, 0),
	(113, 10, 'misdemeanor', 'Exhibition Indécente', 'Exposition volontaire de parties intimes en public.', 10000, 0),
	(114, 10, 'felony', 'Entrave à la Justice', 'Interférence avec les forces de l’ordre ou les procédures judiciaires.', 0, 24),
	(115, 10, 'felony', 'Corruption', 'Offre ou acceptation de quelque chose de valeur pour influencer des décisions.', 100000, 36),
	(117, 10, 'felony', 'Incitation à une Émeute', 'Encourager ou inciter un groupe à adopter un comportement violent.', 0, 48);
